### ISSUE TITLE
Old Client Ping see Protocol Code

### ISSUE THREAD

**Issue by swan201** [BeYkeRYkt/ProtocolSupportVersionControl#6]
After Update ProtocolSupport #288 Commit. Old Clinet see Server ping look like 4-47

**Comment by BeYkeRYkt** [comment]
Version client?

**Comment by swan201** [comment]
@BeYkeRYkt I m testing 1.5.2 ver client.

**Comment by swan201** [comment]
@BeYkeRYkt hello, Shevchik add some get real server version api. maybe you can fix this issue now
